databases:
  - name: blog-app
    databaseName: blog_app_255a
    user: blog_app_255a_user

services:
  - type: web
    name: smart-blog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false